//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: chatcommand.proto

using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace Pmd
{
	public enum ChatType
	{
		ChatType_Map = 2
	}
	public partial class Chat
	{
		public enum Param
		{
			CommonChatUserPmd_CS = 1,
			GMCommandChatUserPmd_C = 2,
			GMCommandListChatUserPmd_S = 4,
			PrivateChatUserPmd_CS = 5
		}
	}
	public partial class CommonChatUserPmd_CS
	{
		public enum ChatType
		{
			ChatType_None = 0,
			ChatType_Lobby = 1,
			ChatType_Room = 2,
			ChatType_Robot = 4
		}
		public enum ChatPos
		{
			ChatPos_None = 0,
			ChatPos_Normal = 1,
			ChatPos_Sys = 2,
			ChatPos_Tips = 4,
			ChatPos_Pop = 8,
			ChatPos_Private = 16,
			ChatPos_Important = 32,
			ChatPos_Honor = 64,
			ChatPos_Gm = 128
		}
		public ulong id { get; set; }
		public string name { get; set; }
		public bool sexman { get; set; }
		/// <summary>
		/// enum ChatPos
		/// </summary>
		public uint chatpos { get; set; }
		/// <summary>
		/// enum ChatType
		/// </summary>
		public uint chattype { get; set; }
		public string info { get; set; }
		/// <summary>
		/// 增加时间戳
		/// </summary>
		public ulong time { get; set; }
	}
	public partial class GMCommandChatUserPmd_C
	{
		public ulong charid { get; set; }
		public string charname { get; set; }
		public string method { get; set; }
		public string @params { get; set; }
	}
	public partial class GMHelpInfo
	{
		public string method { get; set; }
		public string example { get; set; }
	}
	public partial class GMCommandListChatUserPmd_S
	{
		private List<Pmd.GMHelpInfo> m_list;
		[DebuggerNonUserCode]
		public List<Pmd.GMHelpInfo> list
		{
			get { if (this.m_list == null) m_list = new List<Pmd.GMHelpInfo>(); return m_list; }
			set { m_list = value; }
		}
	}
	public partial class PrivateChatUserPmd_CS
	{
		public ulong id { get; set; }
		public string name { get; set; }
		public bool sexman { get; set; }
		public string info { get; set; }
		/// <summary>
		/// 增加时间戳
		/// </summary>
		public ulong time { get; set; }
	}
}
