//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: config.proto

using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace Pmd
{
	/// <summary>
	/// 版本配置文件
	/// </summary>
	public partial class Config
	{
		public enum Version
		{
			Version_Login = 20140427,
			Version_Game = 20140427
		}
		public enum Debug
		{
			Debug_All = 1,
			Debug_Whj = 1
		}
	}
}
