//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: forwardcommand.proto

using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace Pmd
{
	public partial class Forward
	{
		public enum Param
		{
			UserJsMessageForwardUserPmd_CS = 1,
			LoginLobbyReq = 2,
			LoginLobbyRes = 3,
			WebSocketForwardUserPmd_C = 4,
			WebSocketForwardUserPmd_S = 5
		}
	}
	/// <summary>
	/// 长连接时玩家跟区服务器的通信是通过网关转发的,统一用这个消息互相传递
	/// </summary>
	public partial class UserJsMessageForwardUserPmd_CS
	{
		/// <summary>
		/// json消息内容
		/// </summary>
		public string msg { get; set; }
	}
	/// <summary>
	/// HTTP请求切换到websocket链接
	/// </summary>
	public partial class WebSocketForwardUserPmd_C
	{
		/// <summary>
		/// accountid和平台返回给客户端的uid:string是完全不同的两个概念。如果没有在别处提供accountid，此处可临时将uid强转为uint64使用
		/// </summary>
		public ulong accountid { get; set; }
	}
	public partial class WebSocketForwardUserPmd_S
	{
		public ulong accountid { get; set; }
		public string jsongatewayurl { get; set; }
		public ulong tokenid { get; set; }
		public ulong logintempid { get; set; }
	}
}
