//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: nullcommand.proto

using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace Pmd
{
	public enum FrameHeader
	{
		/// <summary>
		/// 0
		/// </summary>
		Bitmask_None = 0,
		/// <summary>
		/// 1 &lt;&lt; 0 表示压缩
		/// </summary>
		Bitmask_Compress = 1,
		/// <summary>
		/// 1 &lt;&lt; 1 表示加密
		/// </summary>
		Bitmask_Encrypt = 2
	}
	public partial class Null
	{
		public enum Param
		{
			ForwardNullUserPmd_CS = 0,
			TickRequestNullUserPmd_CS = 1,
			TickReturnNullUserPmd_CS = 2,
			RequestCloseNullUserPmd_CS = 3,
			FrameHeaderNullUserPmd_CS = 4,
			CheckVersionUserPmd_CS = 5
		}
	}
	public partial class ForwardNullUserPmd_CS
	{
		public uint byCmd { get; set; }
		public uint byParam { get; set; }
		/// <summary>
		/// client use
		/// </summary>
		public uint time { get; set; }
		/// <summary>
		/// server used for forward
		/// </summary>
		public ulong fid { get; set; }
		public byte[] data { get; set; }
		/// <summary>
		/// 0:proto,1:json,2:http
		/// </summary>
		public ulong prototype { get; set; }
		/// <summary>
		/// FrameHeader位枚举
		/// </summary>
		public uint bitmask { get; set; }
	}
	public partial class TickRequestNullUserPmd_CS
	{
		public uint requesttime { get; set; }
	}
	public partial class TickReturnNullUserPmd_CS
	{
		public uint requesttime { get; set; }
		public uint mytime { get; set; }
	}
	public partial class RequestCloseNullUserPmd_CS
	{
		public string reason { get; set; }
	}
	/// <summary>
	/// websocket帧头
	/// </summary>
	public partial class FrameHeaderNullUserPmd_CS
	{
		/// <summary>
		/// FrameHeader位枚举
		/// </summary>
		public uint bitmask { get; set; }
		public byte[] data { get; set; }
	}
	/// <summary>
	/// websocket帧头
	/// </summary>
	public partial class CheckVersionUserPmd_CS
	{
		public uint versionserver { get; set; }
		public uint versionclient { get; set; }
	}
}
