//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: pmd.proto

using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace Pmd
{
	/// <summary>
	/// 平台登陆一级消息
	/// </summary>
	public enum PlatCommand
	{
		PlatCommand_Null = 0,
		/// <summary>
		/// 监控消息
		/// </summary>
		PlatCommand_Monitor = 249,
		/// <summary>
		/// 登陆消息
		/// </summary>
		PlatCommand_Login = 250,
		/// <summary>
		/// 登陆转发消息
		/// </summary>
		PlatCommand_Forward = 251,
		/// <summary>
		/// 第三方对接服务器间消息
		/// </summary>
		PlatCommand_Sdk = 252,
		/// <summary>
		/// 聊天消息
		/// </summary>
		PlatCommand_Chat = 253
	}
	/// <summary>
	/// HTTP请求错误返回定义
	/// </summary>
	public enum HttpReturnCode
	{
		/// <summary>
		/// 无错误
		/// </summary>
		HttpReturnCode_Null = 0,
		/// <summary>
		/// 数据库出错
		/// </summary>
		HttpReturnCode_DbError = 2,
		/// <summary>
		/// 找不到游戏区列表
		/// </summary>
		HttpReturnCode_GameZoneListError = 5,
		/// <summary>
		/// 签名检查错误，需要重新登陆
		/// </summary>
		HttpReturnCode_SignError = 11,
		/// <summary>
		/// 服务器未开
		/// </summary>
		HttpReturnCode_ServerShutDown = 12,
		/// <summary>
		/// Json语法格式错误
		/// </summary>
		HttpReturnCode_JsonSyntaxError = 13,
		/// <summary>
		/// Json消息格式错误
		/// </summary>
		HttpReturnCode_JsonMessageError = 14,
		/// <summary>
		/// tokenvalue为空
		/// </summary>
		HttpReturnCode_TokenValueError = 15,
		/// <summary>
		/// uid与登陆uid不同
		/// </summary>
		HttpReturnCode_WaiGuaUidError = 16,
		/// <summary>
		/// 没有可用网关
		/// </summary>
		HttpReturnCode_NoGatewaytDown = 17,
		/// <summary>
		/// 没有可用Sdk服务器
		/// </summary>
		HttpReturnCode_NoSdkServer = 18,
		/// <summary>
		/// 签名错误
		/// </summary>
		HttpReturnCode_SdkCheckSignErr = 19,
		/// <summary>
		/// 第三方服务器验证错误
		/// </summary>
		HttpReturnCode_Sdk3PartyServerErr = 20,
		/// <summary>
		/// proto解析错误
		/// </summary>
		HttpReturnCode_ProtobufErr = 21,
		/// <summary>
		/// 网关错误
		/// </summary>
		HttpReturnCode_GatewayErr = 22
	}
	/// <summary>
	/// 服务器类型
	/// </summary>
	public enum TaskType
	{
		/// <summary>
		/// 未知
		/// </summary>
		TaskType_Null = 0,
		/// <summary>
		/// 监控服务器
		/// </summary>
		TaskType_Monitor = 1,
		/// <summary>
		/// 登陆服务器
		/// </summary>
		TaskType_Login = 2,
		/// <summary>
		/// 名字验证服务器
		/// </summary>
		TaskType_Name = 3,
		/// <summary>
		/// sdk服务器
		/// </summary>
		TaskType_Sdk = 4,
		/// <summary>
		/// gm服务器
		/// </summary>
		TaskType_Gm = 5,
		/// <summary>
		/// 网关服务器
		/// </summary>
		TaskType_Gateway = 6,
		/// <summary>
		/// 游戏区服务器
		/// </summary>
		TaskType_GameZone = 7
	}
}
