//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: unilightclient.proto

using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace Pmd
{
	public partial class Any
	{
	}
	public partial class HttpPackage
	{
		/// <summary>
		/// 消息类型
		/// </summary>
		public string @do { get; set; }
		private Pmd.Any m_data;
		/// <summary>
		/// 应用层消息内容
		/// </summary>
		[DebuggerNonUserCode]
		public Pmd.Any data
		{
			get { if (this.m_data == null) m_data = new Pmd.Any(); return m_data; }
			set { m_data = value; }
		}
		/// <summary>
		/// 游戏ID
		/// </summary>
		public uint gameid { get; set; }
		/// <summary>
		/// 如果客户端发，服务器照样返回
		/// </summary>
		public uint zoneid { get; set; }
		/// <summary>
		/// 可唯一代表一个用户身份的ID，由平台统一生成
		/// </summary>
		public string uid { get; set; }
		/// <summary>
		/// 组合字段：&lt;平台id&gt;::&lt;平台账户&gt;
		/// </summary>
		public string sid { get; set; }
		/// <summary>
		/// 由PlatTokenLoginReturn返回
		/// </summary>
		public string unigame_plat_login { get; set; }
		/// <summary>
		/// 客户端当前UNIX时间戳，单位秒
		/// </summary>
		public ulong unigame_plat_timestamp { get; set; }
	}
	public partial class HttpPackageReturn
	{
		/// <summary>
		/// 消息类型
		/// </summary>
		public string @do { get; set; }
		private Pmd.Any m_data;
		/// <summary>
		/// 应用层消息内容
		/// </summary>
		[DebuggerNonUserCode]
		public Pmd.Any data
		{
			get { if (this.m_data == null) m_data = new Pmd.Any(); return m_data; }
			set { m_data = value; }
		}
		/// <summary>
		/// 游戏ID
		/// </summary>
		public uint gameid { get; set; }
		/// <summary>
		/// 如果客户端发，服务器照样返回
		/// </summary>
		public uint zoneid { get; set; }
		public Pmd.HttpReturnCode errno { get; set; }
	}
	/// <summary>
	/// 请求区列表【不需要签名】【无时序要求】
	/// </summary>
	public partial class RequestZoneList
	{
	}
	/// <summary>
	/// 选区【必须签名】
	/// </summary>
	public partial class RequestSelectZone
	{
	}
	public partial class RequestSelectZoneReturn
	{
		/// <summary>
		/// 游戏逻辑服务器的http网关地址
		/// </summary>
		public string gatewayurl { get; set; }
	}
	/// <summary>
	/// 平台登录【不需要签名】
	/// </summary>
	public partial class PlatTokenLogin
	{
		private Pmd.PlatInfo m_platinfo;
		/// <summary>
		/// 平台用户信息
		/// </summary>
		[DebuggerNonUserCode]
		public Pmd.PlatInfo platinfo
		{
			get { if (this.m_platinfo == null) m_platinfo = new Pmd.PlatInfo(); return m_platinfo; }
			set { m_platinfo = value; }
		}
	}
	public partial class PlatTokenLoginReturn
	{
		private Pmd.PlatInfo m_platinfo;
		/// <summary>
		/// 平台用户信息
		/// </summary>
		[DebuggerNonUserCode]
		public Pmd.PlatInfo platinfo
		{
			get { if (this.m_platinfo == null) m_platinfo = new Pmd.PlatInfo(); return m_platinfo; }
			set { m_platinfo = value; }
		}
		/// <summary>
		/// 可唯一代表一个用户身份的ID，由平台统一生成
		/// </summary>
		public string uid { get; set; }
		/// <summary>
		/// 组合字段：&lt;平台id&gt;::&lt;平台账户&gt;
		/// </summary>
		public string sid { get; set; }
		/// <summary>
		/// 平台登录密钥，用于上行消息URL签名
		/// </summary>
		public string unigame_plat_key { get; set; }
		/// <summary>
		/// 平台登录token，用于上行消息
		/// </summary>
		public string unigame_plat_login { get; set; }
		/// <summary>
		/// 平台登录token从现在开始多少秒后过期，过期后或服务器返回HttpReturnCode_SignError时客户端需要重新走登陆流程
		/// </summary>
		public uint unigame_plat_login_life { get; set; }
		/// <summary>
		/// 时区的名字
		/// </summary>
		public string timezone_name { get; set; }
		/// <summary>
		/// unilight服务器时区相对于UTC的时间偏移量，单位秒
		/// </summary>
		public int timezone_offset { get; set; }
	}
}
